language: c
before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install bc

script:
  - mkdir toolchain
  - pushd toolchain
  - git clone https://github.com/raspberrypi/tools
  - export PATH=`pwd`/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/:$PATH
  - popd
  - export ARCH=arm
  - export CROSS_COMPILE=arm-linux-gnueabihf-
  - ./build_bal.sh raspi2 do_not_copy
