language: c

before_script:
  - curl http://emdebian.org/tools/debian/emdebian-toolchain-archive.key | sudo apt-key add -
  - echo "deb http://emdebian.org/tools/debian/ jessie main" | sudo tee -a /etc/apt/sources.list
  - sudo dpkg --add-architecture armhf
  - sudo apt-get -qq update
  - sudo apt-get -y install crossbuild-essential-armhf
  
script:
  - ./build_bal.sh raspi1
