language: c

before_script:
  - mkdir toolchain
  - git clone https://github.com/raspberrypi/tools
  - 
  
script:
  - mkdir toolchain
  - git clone https://github.com/raspberrypi/tools
  - export PATH=$pwd/toolchain/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin:$PATH
  - export KERNEL=kernel7
  - make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcm2709_defconfig
