language: c
  
script:
  - mkdir toolchain
  - pushd toolchain
  - git clone https://github.com/raspberrypi/tools
  - export PATH=$pwd/tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin:$PATH
  - popd
  - export KERNEL=kernel7
  - make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcm2709_defconfig
